name: MLflow CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  train-model:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          activate-environment: mlflow-env

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install mlflow pandas numpy scikit-learn

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow run .